export const ghanaAirports = [
  {
    id: '53',
    gmt: null,
    airport_id: '53',
    iata_code: 'ACC',
    city_iata_code: 'ACC',
    icao_code: 'DGAA',
    country_iso2: 'GH',
    geoname_id: '2306104',
    latitude: '5.60737',
    longitude: '-0.171769',
    airport_name: 'Kotoka',
    country_name: 'Ghana',
    phone_number: null,
    timezone: 'Africa/Accra',
  },
  {
    id: '3927',
    gmt: null,
    airport_id: '3927',
    iata_code: 'KMS',
    city_iata_code: 'KMS',
    icao_code: 'DGSI',
    country_iso2: 'GH',
    geoname_id: '6296427',
    latitude: '6.7125',
    longitude: '-1.591111',
    airport_name: 'Kumasi',
    country_name: 'Ghana',
    phone_number: null,
    timezone: 'Africa/Accra',
  },
  {
    id: '5614',
    gmt: null,
    airport_id: '5614',
    iata_code: 'NYI',
    city_iata_code: 'NYI',
    icao_code: 'DGSN',
    country_iso2: 'GH',
    geoname_id: '6296428',
    latitude: '7.333333',
    longitude: '-2.333333',
    airport_name: 'Sunyani',
    country_name: 'Ghana',
    phone_number: null,
    timezone: 'Africa/Accra',
  },
  {
    id: '7742',
    gmt: null,
    airport_id: '7742',
    iata_code: 'TKD',
    city_iata_code: 'TKD',
    icao_code: 'DGTK',
    country_iso2: 'GH',
    geoname_id: '6296430',
    latitude: '4.891667',
    longitude: '-1.775',
    airport_name: 'Takoradi',
    country_name: 'Ghana',
    phone_number: null,
    timezone: 'Africa/Accra',
  },
  {
    id: '7800',
    gmt: null,
    airport_id: '7800',
    iata_code: 'TML',
    city_iata_code: 'TML',
    icao_code: 'DGLE',
    country_iso2: 'GH',
    geoname_id: '6296422',
    latitude: '9.406944',
    longitude: '-0.879167',
    airport_name: 'Tamale',
    country_name: 'Ghana',
    phone_number: null,
    timezone: 'Africa/Accra',
  },
  {
    id: '46',
    gmt: '1',
    airport_id: '46',
    iata_code: 'ABV',
    city_iata_code: 'ABV',
    icao_code: 'DNAA',
    country_iso2: 'NG',
    geoname_id: '7649170',
    latitude: '9.004614',
    longitude: '7.270447',
    airport_name: 'Nnamdi Azikiwe International Airport',
    country_name: 'Nigeria',
    phone_number: null,
    timezone: 'Africa/Lagos',
  },
  {
    id: '4458',
    gmt: '1',
    airport_id: '4458',
    iata_code: 'LOS',
    city_iata_code: 'LOS',
    icao_code: 'DNMM',
    country_iso2: 'NG',
    geoname_id: '2332459',
    latitude: '6.577871',
    longitude: '3.321178',
    airport_name: 'Murtala Muhammed',
    country_name: 'Nigeria',
    phone_number: null,
    timezone: 'Africa/Lagos',
  },
];
